id: IC6CD4CC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:29:27+00:00'
last_modified: '2022-06-09T08:17:45.656734+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23698
  title: ཁ་སྐྱོང་བྲག་པ་ཅེར་སྒོམ་རིན་པོ་ཆེའི་མགུར་འབུམ་དང་ཟིན་བྲིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51C5:
      image_group_id: I0846
      title: ''
      total_pages: 509
      order: 1
      base_file: 51C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
