id: P007983
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:16.719101
source_metadata:
  id: bdr:W23698
  title: ཁ་སྐྱོང་བྲག་པ་ཅེར་སྒོམ་རིན་པོ་ཆེའི་མགུར་འབུམ་དང་ཟིན་བྲིས།
  author: ''
  volumes:
    cd3e08392e224262b2035ff6068be216:
      image_group_id: I0846
      title: ''
      volume_number: 1
      total_pages: 509
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
